import { Plato } from './types';

export const PAISES = [
  'España',
  'Italia',
  'Francia',
  'México',
  'Japón',
  'China',
  'India',
  'Estados Unidos',
  'Tailandia',
  'Marruecos',
  'Grecia',
  'Perú',
  'Internacional',
];

export const COUNTRY_CODES: { [key: string]: string } = {
  'España': 'es',
  'Italia': 'it',
  'Francia': 'fr',
  'México': 'mx',
  'Japón': 'jp',
  'China': 'cn',
  'India': 'in',
  'Estados Unidos': 'us',
  'Tailandia': 'th',
  'Marruecos': 'ma',
  'Grecia': 'gr',
  'Perú': 'pe',
  'Internacional': 'un',
};

export const INGREDIENT_CATEGORIES_LIST = [
  'Frutas y Verduras',
  'Carne',
  'Pescado y Marisco',
  'Lácteos y Huevos',
  'Panadería y Repostería',
  'Despensa y Secos',
  'Bebidas',
  'Otros',
];

export const UNIDADES_INGREDIENTES = [
  'cucharada',
  'cucharadita',
  'gr',
  'kg',
  'l',
  'lata',
  'manojo',
  'ml',
  'pizca',
  'unidades',
];

export const INITIAL_UTENSILS: string[] = [
  'Bandeja de horno',
  'Cuchara madera',
  'Cuchillos',
  'Espumadera',
  'Freidora',
  'Horno',
  'Licuadora',
  'Microondas',
  'Mortero',
  'Olla',
  'Olla a presión',
  'Picador',
  'Pinzas',
  'Sarten',
  'Tabla de cortar',
  'Tenedor madera',
  'Tostadora',
].sort((a, b) => a.localeCompare(b));


export const INITIAL_DISHES: Plato[] = [
  // --- Platos de España ---
  {
    id: 'es-1',
    nombre: 'Tortilla de Patatas',
    pais: 'España',
    raciones: 4,
    tiempo_preparacion: 25,
    dificultad: 'Fácil',
    tipo_plato: 'plato_principal',
    valido_para: ['comida', 'cena'],
    ingredientes: [
      { nombre: 'Huevos', cantidad: 6, unidad: 'unidades', categoria_ingrediente: 'Lácteos y Huevos', opcional: false },
      { nombre: 'Patatas', cantidad: 500, unidad: 'gr', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Cebolla', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Aceite de oliva', cantidad: 100, unidad: 'ml', categoria_ingrediente: 'Despensa y Secos', opcional: false },
      { nombre: 'Sal', cantidad: 5, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: false },
    ],
    receta_url: 'https://www.directoalpaladar.com/recetas-de-huevos-y-tortillas/como-hacer-tortilla-de-patatas-perfecta-receta-tradicional-espanola',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    alergenos: ['Huevos'],
    utensilios: ['Sarten', 'bol', 'espumadera'],
    sugerencias: 'Para una tortilla más jugosa, no cuajarla en exceso.'
  },
  {
    id: 'es-2',
    nombre: 'Gazpacho Andaluz',
    pais: 'España',
    raciones: 6,
    tiempo_preparacion: 15,
    dificultad: 'Fácil',
    tipo_plato: 'plato_entrante',
    valido_para: ['comida'],
    ingredientes: [
      { nombre: 'Tomates maduros', cantidad: 1000, unidad: 'gr', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Pimiento verde', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Pepino', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Diente de ajo', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Pan de hogaza', cantidad: 50, unidad: 'gr', categoria_ingrediente: 'Panadería y Repostería', opcional: true },
      { nombre: 'Aceite de oliva virgen extra', cantidad: 50, unidad: 'ml', categoria_ingrediente: 'Despensa y Secos', opcional: false },
      { nombre: 'Vinagre de Jerez', cantidad: 30, unidad: 'ml', categoria_ingrediente: 'Despensa y Secos', opcional: false },
      { nombre: 'Sal', cantidad: 5, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: false },
    ],
    receta_url: 'https://www.directoalpaladar.com/recetas-de-sopas-y-cremas/receta-de-gazpacho-andaluz-tradicional-la-mejor-para-un-resultado-perfecto',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    alergenos: ['Gluten'],
    utensilios: ['batidora', 'colador chino'],
  },
  {
    id: 'es-3',
    nombre: 'Ensaladilla Rusa',
    pais: 'España',
    raciones: 4,
    tiempo_preparacion: 40,
    dificultad: 'Fácil',
    tipo_plato: 'plato_entrante',
    valido_para: ['comida', 'cena'],
    ingredientes: [
        { nombre: 'Patatas', cantidad: 500, unidad: 'gr', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
        { nombre: 'Zanahorias', cantidad: 2, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
        { nombre: 'Guisantes congelados', cantidad: 150, unidad: 'gr', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
        { nombre: 'Huevos', cantidad: 2, unidad: 'unidades', categoria_ingrediente: 'Lácteos y Huevos', opcional: false },
        { nombre: 'Atún en aceite', cantidad: 150, unidad: 'gr', categoria_ingrediente: 'Pescado y Marisco', opcional: false },
        { nombre: 'Mayonesa', cantidad: 200, unidad: 'gr', categoria_ingrediente: 'Lácteos y Huevos', opcional: false },
        { nombre: 'Aceitunas', cantidad: 50, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: true },
    ],
    receta_url: 'https://www.hogarmania.com/cocina/recetas/ensaladas/ensaladilla-rusa-tradicional-karlos-arguinano.html',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    alergenos: ['Huevos', 'Pescado'],
    utensilios: ['olla', 'bol'],
  },
  {
    id: 'es-4',
    nombre: 'Pollo al Horno con Verduras',
    pais: 'España',
    raciones: 4,
    tiempo_preparacion: 75,
    dificultad: 'Fácil',
    tipo_plato: 'plato_unico',
    valido_para: ['comida'],
    ingredientes: [
      { nombre: 'Pollo entero', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Carne', opcional: false },
      { nombre: 'Patatas', cantidad: 4, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Cebolla', cantidad: 2, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Pimiento rojo', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Limón', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Vino blanco', cantidad: 100, unidad: 'ml', categoria_ingrediente: 'Bebidas', opcional: false },
      { nombre: 'Tomillo', cantidad: 5, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: false },
    ],
    receta_url: 'https://www.hogarmania.com/cocina/recetas/carnes/pollo-asado-horno-verduras-patatas-2708.html',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    utensilios: ['Bandeja de horno'],
  },
  {
    id: 'es-5',
    nombre: 'Lentejas Estofadas',
    pais: 'España',
    raciones: 4,
    tiempo_preparacion: 50,
    dificultad: 'Fácil',
    tipo_plato: 'plato_unico',
    valido_para: ['comida'],
    ingredientes: [
      { nombre: 'Lentejas pardinas', cantidad: 300, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: false },
      { nombre: 'Chorizo', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Carne', opcional: false },
      { nombre: 'Zanahoria', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Cebolla', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Patata', cantidad: 1, unidad: 'unidades', categoria_ingrediente: 'Frutas y Verduras', opcional: false },
      { nombre: 'Pimentón', cantidad: 5, unidad: 'gr', categoria_ingrediente: 'Despensa y Secos', opcional: false },
    ],
    receta_url: 'https://www.directoalpaladar.com/recetas-de-legumbres-y-verduras/lentejas-guisadas-receta-tradicional-de-la-abuela',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    utensilios: ['Olla'],
  },
  {
    id: 'es-8',
    nombre: 'Flan Casero de Huevo',
    pais: 'España',
    raciones: 6,
    tiempo_preparacion: 60,
    dificultad: 'Media',
    tipo_plato: 'postre',
    valido_para: ['comida', 'cena'],
    ingredientes: [
        { nombre: 'Huevos', cantidad: 4, unidad: 'unidades', categoria_ingrediente: 'Lácteos y Huevos', opcional: false },
        { nombre: 'Leche entera', cantidad: 500, unidad: 'ml', categoria_ingrediente: 'Lácteos y Huevos', opcional: false },
        { nombre: 'Azúcar', cantidad: 150, unidad: 'gr', categoria_ingrediente: 'Panadería y Repostería', opcional: false },
        { nombre: 'Esencia de vainilla', cantidad: 5, unidad: 'ml', categoria_ingrediente: 'Panadería y Repostería', opcional: true },
    ],
    receta_url: 'https://www.directoalpaladar.com/postres/flan-de-huevo-casero-la-receta-tradicional-de-la-abuela-que-siempre-sale-bien',
    instrucciones: { modo: 'texto', contenido: 'Añade aquí las instrucciones de tu receta...' },
    alergenos: ['Huevos', 'Lácteos'],
    utensilios: ['flanera', 'horno', 'varillas'],
  },
];